// Demo data used when Supabase is not yet connected

export const MOCK_USER_ID = 'mock-user-1'

export const MOCK_PROFILE = {
  id: MOCK_USER_ID,
  email: 'demo@littlebookexchange.com',
  username: 'demouser',
  name: 'Demo User',
  city: 'Chicago',
  state: 'IL',
  phone: '(312) 555-0100',
  contact_preference: 'email',
  address: '742 Evergreen Terrace',
  address_unit: '',
  share_address: true,
  pickup_description: 'front porch',
  share_pickup: true,
}

export const MOCK_LISTINGS = [
  {
    id: 'mock-1',
    user_id: 'mock-user-2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    condition: 'Good',
    price: 1,
    description: 'A classic American novel in great condition. Light wear on the cover but pages are clean and unmarked.',
    city: 'Chicago',
    state: 'IL',
    genre: 'Fiction',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    profiles: { name: 'Sarah M.', city: 'Chicago' },
  },
  {
    id: 'mock-2',
    user_id: 'mock-user-3',
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    condition: 'Well-Loved',
    price: 1,
    description: 'Beloved copy, well-loved but all pages intact. Great for a new reader discovering the magic!',
    city: 'Chicago',
    state: 'IL',
    genre: 'Fantasy',
    format: 'Hardcover',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    profiles: { name: 'Tom K.', city: 'Chicago' },
  },
  {
    id: 'mock-3',
    user_id: 'mock-user-4',
    title: 'Educated',
    author: 'Tara Westover',
    condition: 'Good',
    price: 1,
    description: 'Incredible memoir, barely read. Spine is tight, no markings.',
    city: 'Evanston',
    state: 'IL',
    genre: 'Memoir',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    profiles: { name: 'Maria L.', city: 'Evanston' },
  },
  {
    id: 'mock-4',
    user_id: 'mock-user-5',
    title: 'Atomic Habits',
    author: 'James Clear',
    condition: 'Fair',
    price: 1,
    description: 'Some highlighting in the first few chapters, otherwise clean. Life-changing read.',
    city: 'Oak Park',
    state: 'IL',
    genre: 'Self-Help',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    profiles: { name: 'James R.', city: 'Oak Park' },
  },
  {
    id: 'mock-5',
    user_id: 'mock-user-6',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    condition: 'Good',
    price: 1,
    description: 'Classic Tolkien in solid condition.',
    city: 'Chicago',
    state: 'IL',
    genre: 'Fantasy',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    profiles: { name: 'Anya B.', city: 'Chicago' },
  },
  {
    id: 'mock-6',
    user_id: 'mock-user-7',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    condition: 'Good',
    price: 1,
    description: 'Gorgeous story. Read once, kept in excellent condition.',
    city: 'Naperville',
    state: 'IL',
    genre: 'Fiction',
    format: 'Hardcover',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    profiles: { name: 'Claire D.', city: 'Naperville' },
  },
  {
    id: 'mock-7',
    user_id: 'mock-user-8',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    condition: 'Good',
    price: 1,
    description: 'Mind-expanding book. No markings, clean pages.',
    city: 'Chicago',
    state: 'IL',
    genre: 'History',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    profiles: { name: 'Dev P.', city: 'Chicago' },
  },
  {
    id: 'mock-8',
    user_id: MOCK_USER_ID,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    condition: 'Fair',
    price: 1,
    description: 'A timeless classic. Slightly worn cover, all pages present.',
    city: 'Chicago',
    state: 'IL',
    genre: 'Fiction',
    format: 'Paperback',
    status: 'active',
    photo_url: null,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    profiles: { name: 'Demo User', city: 'Chicago' },
  },
]

export const MOCK_MESSAGES_BY_CONVO: Record<string, any[]> = {
  'mock-convo-1': [
    { id: 'msg-1', conversation_id: 'mock-convo-1', sender_id: 'mock-user-2', body: 'Hi! Is this still available?', created_at: new Date(Date.now() - 3600000 * 3).toISOString() },
    { id: 'msg-2', conversation_id: 'mock-convo-1', sender_id: MOCK_USER_ID,   body: 'Yes it is! Would you like to meet this weekend?', created_at: new Date(Date.now() - 3600000 * 2).toISOString() },
    { id: 'msg-3', conversation_id: 'mock-convo-1', sender_id: 'mock-user-2', body: 'Saturday afternoon works great for me!', created_at: new Date(Date.now() - 3600000).toISOString() },
  ],
  'mock-convo-2': [
    { id: 'msg-4', conversation_id: 'mock-convo-2', sender_id: 'mock-user-3', body: 'Would you take $3 for Educated?', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: 'msg-5', conversation_id: 'mock-convo-2', sender_id: MOCK_USER_ID,   body: "I'm asking $5 but happy to meet in the middle at $4!", created_at: new Date(Date.now() - 82800000).toISOString() },
  ],
}

export const MOCK_CONVERSATIONS = [
  {
    id: 'mock-convo-1',
    listing_id: 'mock-1',
    buyer_id: 'mock-user-2',
    seller_id: MOCK_USER_ID,
    exchange_status: 'requested',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    listings: MOCK_LISTINGS[0],
    buyer:  { id: 'mock-user-2', username: 'sarahm', name: 'Sarah M.', city: 'Chicago', state: 'IL', phone: '(312) 555-0101' },
    seller: { id: MOCK_USER_ID,  username: 'demouser', name: 'Demo User', city: 'Chicago', state: 'IL', phone: '(312) 555-0100' },
    messages: MOCK_MESSAGES_BY_CONVO['mock-convo-1'],
  },
  {
    id: 'mock-convo-2',
    listing_id: 'mock-3',
    buyer_id: 'mock-user-3',
    seller_id: MOCK_USER_ID,
    exchange_status: 'none',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    listings: MOCK_LISTINGS[2],
    buyer:  { id: 'mock-user-3', username: 'tomk', name: 'Tom K.', city: 'Chicago', state: 'IL', phone: '(312) 555-0102' },
    seller: { id: MOCK_USER_ID,  username: 'demouser', name: 'Demo User', city: 'Chicago', state: 'IL', phone: '(312) 555-0100' },
    messages: MOCK_MESSAGES_BY_CONVO['mock-convo-2'],
  },
  {
    id: 'mock-convo-3',
    listing_id: 'mock-4',
    buyer_id: MOCK_USER_ID,
    seller_id: 'mock-user-5',
    exchange_status: 'confirmed',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    listings: MOCK_LISTINGS[3],
    buyer:  { id: MOCK_USER_ID,  username: 'demouser', name: 'Demo User', city: 'Chicago', state: 'IL', phone: '(312) 555-0100' },
    seller: { id: 'mock-user-5', username: 'jamesr', name: 'James R.', city: 'Oak Park', state: 'IL', phone: '(708) 555-0105', address: '555 Oak Ave', address_unit: 'Unit 3', share_address: true, pickup_description: 'back porch, ring doorbell', share_pickup: true },
    messages: [],
  },
]
